### ISSUE TITLE
Create top-level Source directory

### ISSUE THREAD

**Issue by buckd** [ni/niveristand-scan-engine-ethercat-custom-device#121]
The top-level source directory in this repo is `Custom Device Source`. This makes things a little confusing now that there are scripting examples #120. In all our other repos, the top-level directory is `Source`. We should change this repo to have the same structure.

**Comment by Karl-G1** [comment]
I'm closing this issue for now. Since I missed renaming the top-level directory in #171, we are unlikely to want to re-link everything in the custom device source for a second time just to rename the source folder.
