### ISSUE TITLE
Set minimum version for Scan Engine tests

### ISSUE THREAD

**Issue by buckd** [ni/niveristand-scan-engine-ethercat-custom-device#13]
The Scan Engine custom device tests can only be run for VeriStand 2017 and later. These tests should be skipped if running in older versions. This can be accomplished by passing a minimum version to OpenVeriStandConnection.vi in the test tools. See [here](https://github.com/ni/niveristand-engine-simulation-toolkit-custom-device/pull/35).

**Comment by rtzoeller** [comment]
The source for the custom device is now written in 2017, as such this is no longer an issue.
