### ISSUE TITLE
Bug in DBL and SGL support for 3rd party EtherCAT slaves

### ISSUE THREAD

**Issue by keprt** [ni/niveristand-scan-engine-ethercat-custom-device#19]
**Description**
If the 3rd party slaves contains DBL or SGL scan engine variable type, SEECD fails on deploy.

**Steps to reproduce the behavior**
Add 3rd party slave, that has DBL or SGL datatype. Autodetect modules. Deploy

**Expected behavior**
System should be able to read and write DBL and SGL variables properly.

**Screenshots**
Printscreens from **fixed** version:
UDV Data Type.ctl needs to get DBL and SGL item
![image](https://user-images.githubusercontent.com/8394296/53026779-e16e0000-3463-11e9-8248-3bc9edc3d2ed.png)

TypeCodeToEnum needs Case A and 9
![image](https://user-images.githubusercontent.com/8394296/53027284-f1d2aa80-3464-11e9-9516-21e26f601564.png)

Write and Read needs SGL and DBL case
![image](https://user-images.githubusercontent.com/8394296/53027363-129b0000-3465-11e9-9fa6-c42bfe1417a7.png)

![image](https://user-images.githubusercontent.com/8394296/53027409-26466680-3465-11e9-8e18-a4db5e4f71fc.png)

**Desktop (please complete the following information):**
 - OS: all RT

**Additional context**
I've already implemented a fix for customer based on older version of SEECD. So you could contact me and we could do a merge together.

**Comment by rtzoeller** [comment]
@keprt can you list some examples of devices which are broken by this? It would be nice to have for validation.

**Comment by keprt** [comment]
@rtzoeller probably don't want to list all here. I will send you email

**Comment by fmussi** [comment]
I don't know if this is the right place, but with the 4.5 version that we ship with VS 2019R2, I cannot read SGL variables. I always get 0 values where LV or Distributed system manager returns the correct SGL value. Is it a known issue?

**Comment by rtzoeller** [comment]
@fmussi that is the expected behavior; this issue is still open.

This is not an issue we are actively prioritizing in the backlog, however we would welcome a pull request adding support if you are able to validate the functionality.
