### ISSUE TITLE
Custom Device User Help Documentation

### ISSUE THREAD

**Issue by tarmanan** [ni/niveristand-scan-engine-ethercat-custom-device#226]
**Is your feature request related to a problem? Please describe.**
Help documentation for the Scan Engine and EtherCAT custom device requires external sources such as LabVIEW, web help documents

**Describe the solution you'd like**
Most of our VeriStand / Scan Engine and EtherCAT Custom Device installations do not have LabVIEW installed or internet access. 
Our team has very little LabVIEW experience.  For example, to find information on configuration of specialty digital settings, it requires using a PC with LabVIEW and/or internet access to understand configuration settings

**Describe alternatives you've considered**
PC with LabVIEW and/or internet access

**Additional context**
![image](https://user-images.githubusercontent.com/46938263/221901872-4043b77c-6dae-41fd-a4e0-d81bfbd2af3b.png)

![image](https://user-images.githubusercontent.com/46938263/221901962-2beabd99-c547-4863-86f2-96495babd90e.png)

**Comment by Karl-G1** [comment]
@tarmanan 
Would adding a simple button to the Slot page that launches the help be a good enough solution? We could include the CompactRIO and C Series CHM files in the Scan Engine Custom Device directory, then link to it from the page fairly easily for something like this:
![image](https://user-images.githubusercontent.com/31290917/222263299-4229de53-cbdf-4ff6-b966-10a2acbbf0e3.png)

I could see a solution where we link to the specific module's help page once it is selected (requiring a change in the [modules libraries](https://github.com/ni/niveristand-scan-engine-module-libraries) which serves the sub-panels with the configuration options). However, that would take a lot more time to implement.

**Comment by tarmanan** [comment]
@Karl-G1 , this would be an excellent solution!

**Comment by Karl-G1** [comment]
This fix will be included in the next release. Closing issue.
