### ISSUE TITLE
Outdated documentation in repository

### ISSUE THREAD

**Issue by rtzoeller** [ni/niveristand-scan-engine-ethercat-custom-device#50]
**Describe the bug**
There is a README and a spreadsheet of module support in a subdirectory of the repository. This content is outdated, and should be removed or updated.

https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/tree/master/Custom%20Device%20Source/Docs

**Expected behavior**
Update or remove it.

**Comment by Karl-G1** [comment]
Fixed in #171 (files were deleted)
