### ISSUE TITLE
Error 537702 while deploying to crio 9047 and crio 9040

### ISSUE THREAD

**Issue by hhb-alt** [ni/niveristand-scan-engine-ethercat-custom-device#65]
Precondition:
1. Veristand version 2019 & 2019 R2
2. scan-engine-ethercat-custom-device verision 19.2.0.5,19.1.0.5,19.0.0.11
3. Crio 9047 with NI 9403 on slot1(or Crio 9040 with NI 9403 on slot2)

steps:
 1.create a new labview fpga project
 2.add NI9403 into "real time scan resources"
 3.add an empty vi into fpga
 4. compile and get a bitfile
 5.create a new veristand project with crio 9047 or crio 9040
 6.add scan engine custom devcie, leave NI 9403 slot empty. It's running perfect
 7.Select NI9403, it continues report error 537702. configureation mismatch

![图片](https://user-images.githubusercontent.com/59386369/71614382-3fbc5100-2be6-11ea-91b6-fdb3a38c83c2.png)
![图片](https://user-images.githubusercontent.com/59386369/71614571-6a5ad980-2be7-11ea-842f-dfdc28bfd65f.png)
![图片](https://user-images.githubusercontent.com/59386369/71614581-78a8f580-2be7-11ea-82e3-5b66f18b92df.png)

**Comment by buckd** [comment]
@hhb-alt Did you auto-detect the 9203 in System Explorer or did you manually change the module type? The cRIO-904x requires the module mode to be set on a per-module basis, not a per-chassis basis like previous models. There is a known issue with VeriStand for the Controller settings (in your case the `dcc` target), where the **FPGA / Scan interface mode** will not correctly set the mode for per-module targets.

The [19.0.0 release](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/releases/tag/v19.0.0) of the custom device added support for changing the mode during auto-detect, but if you manually added the module, this code does not execute. In order to make sure the configurations match, you'll need to open **NI MAX** and make sure to configure the module there to use the `Real-Time Scan (IO Variables)` **Programming Mode**.

**Comment by hhb-alt** [comment]
@buckd Thank for reply. I've tried both auto-detect and manually change. Auto-detect will remove all configuration and I have to manually add local chasis and modules again. Here are the steps:
1.This was the beginning. I manually added the configuration. It looked like this
![图片](https://user-images.githubusercontent.com/59386369/71703318-f6027f00-2e0e-11ea-97f9-dbe1bbbb43a8.png)
2.Then I chose auto-detect modules
![图片](https://user-images.githubusercontent.com/59386369/71703365-1cc0b580-2e0f-11ea-8c5a-0257ac16f232.png)
3.This showed a warning.
![图片](https://user-images.githubusercontent.com/59386369/71703381-3104b280-2e0f-11ea-9994-2147bb2158dc.png)
4.Then the local chasis was gone
![图片](https://user-images.githubusercontent.com/59386369/71703407-4e398100-2e0f-11ea-8762-1a1d8e52635b.png)
5. I clicked the auto-detect again. Local chasis wouldn't be back.
6. Then have to add local chassis again. Add modules,just like step 1.
7. In NI MAX ,module were in "real time scan IO" mode
![图片](https://user-images.githubusercontent.com/59386369/71703531-07985680-2e10-11ea-866e-a1471fb82f5f.png)
8.Once I deployed veristand. Veristand will report 537702 error and stop. Inside NI max, I could observed the 2 modules were change to "labview FPGA" mode automatically.
![图片](https://user-images.githubusercontent.com/59386369/71703613-83929e80-2e10-11ea-8cc2-7031b1f58719.png)

**Comment by buckd** [comment]
This looks like it stems from the fact that selecting a custom bitfile causes an automatic selection of **FPGA Mode** for the _FPGA / Scan interface mode_ setting on the controller page.

After you select your custom bitfile, go back to your controller page (_dcc_) and you will see **FPGA Mode** has been selected. Try changing the mode back to **Use current** before you deploy. When I made that change, I was able to successfully deploy (you will need to reset the mode to **Real-Time Scan IO** in MAX before doing this). Let me know if this works for you.

Note that any time you change the custom bitfile configuration, this setting will get changed back to **FPGA Mode**, so make sure you set this value after importing your bitfile.

I'm not sure why the auto-detect is failing, but I was able to reproduce that also, but only after a failed deployment. I'll create an issue for that too.

**Comment by hhb-alt** [comment]
@buckd Thanks again. Following  your advice, I changed NI 9403 and 9205 to real time scan mode ,   "FPGA/Scan interface mode" to "use current", it's working perfectly.
![图片](https://user-images.githubusercontent.com/59386369/71791689-e2eee980-3070-11ea-8fc4-ec1d097a4f8a.png)
I thought it's the "scan engine " changed the working mode of crio 904x. It seems  it is because veristand itself. 
"use current": means module mode will not  be changed
"FPGA mode":means all module  will be changed  to FPGA mode 
"Scan  mode":means  all module will be changed  to scan mode.
I will close this issue . Thanks again.
