### ISSUE TITLE
Add 9216 Support

### ISSUE THREAD

**Issue by AshleyNunn** [ni/niveristand-scan-engine-ethercat-custom-device#76]
ashley.nunn@ni.com
I am TSE in the UK office.

The 9217 is supported, but I need support for the 9216 module for the extra channel density. 

We are happy to create a branch and add this support ourselves but want to follow the best guidelines so that you can verify the edits and use this for a future release of the CD. 

Please contact me for more details

**Comment by Karl-G1** [comment]
This was addressed in PR #77 and will be available in the next release of the custom device.
