### ISSUE TITLE
Can't build the Configuration LLB

### ISSUE THREAD

**Issue by andresyie** [ni/niveristand-scan-engine-ethercat-custom-device#86]
**Please describe the problem you're facing.**
I'm trying to build this Custom Device but I'm Having problems with Configuration LLB. When I try to build the Configuration specification I get and a error saying some VIs broken during the building. I can trace this broken VIs back to the Modules.lvlibp.

**Describe troubleshooting steps you've taken.**
I tried several versions and also I reinstalled LabVIEW. 

**Additional context**
![Error](https://user-images.githubusercontent.com/66782517/84503289-3d444400-acba-11ea-8b2e-bc0cc8bce856.png)
![Error1](https://user-images.githubusercontent.com/66782517/84503368-5f3dc680-acba-11ea-8d0b-d25e57964560.png)

Thanks.

**Comment by buckd** [comment]
@andresyie, from the pictures above, your LabVIEW project has not loaded `Modules.lvlibp`, which likely means one of two things. Either the library does not exist on disk where it is expected, or it does exist, but is built for a different LabVIEW version or operating system.

The library is not part of the repo. It must be built from [niveristand-scan-engine-module-libraries](https://github.com/ni/niveristand-scan-engine-module-libraries) or copied from the [latest release](https://github.com/ni/niveristand-scan-engine-module-libraries/releases) from that repo.

Note that you will also need the `NI ECAT Remote IO.llb` from the same repo mentioned above and the [FXP.llb](https://github.com/ni/niveristand-scan-engine-fxp-libraries) library. All of these should be copied to the `Custom Device Source` directory before loading the project.

**Comment by andresyie** [comment]
> ote that you will also need the `NI ECAT Remote IO.llb`

Thanks for the fast answer. You are right. I buildt the modules.lvlibp for a RT PXI Target but the configuration.llb is for windows since I´m deploying from a windows 10 PC to a PXI. How can I build a configuration.llb for a windows machine if there is no  modules.lvlibp for windows? Im the project I download I only see for RT, VxWorks, and Linux, 

Thanks.

**Comment by buckd** [comment]
> How can I build a configuration.llb for a windows machine if there is no modules.lvlibp for windows? Im the project I download I only see for RT, VxWorks, and Linux,

You're correct. There is not a Windows build of the modules. This is an unfortunate artifact of when this custom device was created long ago. From LabVIEW's perspective, Windows and Pharlap are very similar, and, in this case, the Pharlap binaries can also be loaded on Windows. So, if you copy the Pharlap RT libraries to the `Custom Device Source` directory and then load the project and try to build the `Configuration.llb`, you should be successful.

**Comment by andresyie** [comment]
> 
> 
> > How can I build a configuration.llb for a windows machine if there is no modules.lvlibp for windows? Im the project I download I only see for RT, VxWorks, and Linux,
> 
> You're correct. There is not a Windows build of the modules. This is an unfortunate artifact of when this custom device was created long ago. From LabVIEW's perspective, Windows and Pharlap are very similar, and, in this case, the Pharlap binaries can also be loaded on Windows. So, if you copy the Pharlap RT libraries to the `Custom Device Source` directory and then load the project and try to build the `Configuration.llb`, you should be successful.

Thanks for the anwer. I builded the RT libraries and put them in the Custom Device Source but now when I try to open the Custom Device Project I get a crash. Any ideas?
![Crash](https://user-images.githubusercontent.com/66782517/84859863-3e84c080-b06e-11ea-9642-14051bc13a6c.png)

Thanks again for helping :).

**Comment by Karl-G1** [comment]
Fixed via documentation in #101
